### PR TITLE
Undefined check in listener

### PR DESCRIPTION
**Pull request by mdwragg**
Polymer 2 erroring in px-tree due to selected being undefined.

### CODE REVIEW

**Comment by mdwragg** [comment]
Comforting words as always ;)

**Comment by mdwragg** [comment]
@davidrleonard Shout at us if we did a bad thing...

**Comment by davidrleonard** [comment]
Looks good to me at a glance, thanks for the fix. The test suite for these behaviors should cover expected outcomes so if it passes, all should be well. 🎉

**Comment by mdwragg** [comment]
Nice one bruv. Thanks.

**Pull request merged**
